SET IDENTITY_INSERT [dbo].[CustomerMaster] ON
INSERT INTO [dbo].[CustomerMaster] ([CustomerId], [CustomerName], [Password], [Address], [Age], [CountryCode], [Email], [Gender], [PhoneNumber], [IdVerificationType]) VALUES (1, N'Abhinav Singh', N'Abhsing123', N'MadhyabPradesh', 27, 91, N'abhsingh@gmail.com', N'male', N'1225454865', N'Adhaar card')
INSERT INTO [dbo].[CustomerMaster] ([CustomerId], [CustomerName], [Password], [Address], [Age], [CountryCode], [Email], [Gender], [PhoneNumber], [IdVerificationType]) VALUES (2, N'Gaurav Kumar', N'gaukum123', N'UttarPradesh', 28, 9, N'dvnsjvh@gmail.com', N'male', N'2546565461', N'Pan Card')
INSERT INTO [dbo].[CustomerMaster] ([CustomerId], [CustomerName], [Password], [Address], [Age], [CountryCode], [Email], [Gender], [PhoneNumber], [IdVerificationType]) VALUES (3, N'Megha Chavan', N'mdjvniuv123', N'Maharashtra', 25, 91, N'jdvnijvh@gmail.com', N'female', N'1565464664', N'adhar card')
INSERT INTO [dbo].[CustomerMaster] ([CustomerId], [CustomerName], [Password], [Address], [Age], [CountryCode], [Email], [Gender], [PhoneNumber], [IdVerificationType]) VALUES (4, N'farhan', N'bsvsiuhvi124', N'Delhi', 26, 94, N'kjdnviuhv@gmail.com', N'male', N'1546466584', N'adhar card')
INSERT INTO [dbo].[CustomerMaster] ([CustomerId], [CustomerName], [Password], [Address], [Age], [CountryCode], [Email], [Gender], [PhoneNumber], [IdVerificationType]) VALUES (5, N'vedant', N'jdnuivh152', N'Mumbsi', 26, 94, N'kdniuvh@gmail.com', N'male', N'5464664984', N'pass port')
INSERT INTO [dbo].[CustomerMaster] ([CustomerId], [CustomerName], [Password], [Address], [Age], [CountryCode], [Email], [Gender], [PhoneNumber], [IdVerificationType]) VALUES (7, N'swapnali', N'jdvhwiuvh85', N'nashik', 25, 95, N'djsiuvsvhdu@gmail.com', N'female', N'1265468654', N'pass port')
INSERT INTO [dbo].[CustomerMaster] ([CustomerId], [CustomerName], [Password], [Address], [Age], [CountryCode], [Email], [Gender], [PhoneNumber], [IdVerificationType]) VALUES (8, N'nishant', N'jhcqafcgqafq454451', N'nashik', 26, 96, N'jfnwsbuhv@gmail.com', N'male', N'9486465491', N'adhar card')
INSERT INTO [dbo].[CustomerMaster] ([CustomerId], [CustomerName], [Password], [Address], [Age], [CountryCode], [Email], [Gender], [PhoneNumber], [IdVerificationType]) VALUES (9, N'sagar ghutke', N'dniuqvciau2154', N'madhya pradesh', 24, 95, N'jdvwuivueeui@gmail.com', N'male', N'9465846514', N'pass port')
INSERT INTO [dbo].[CustomerMaster] ([CustomerId], [CustomerName], [Password], [Address], [Age], [CountryCode], [Email], [Gender], [PhoneNumber], [IdVerificationType]) VALUES (10, N'jeevan ', N'jdhquihde213e123', N'nagpur', 28, 96, N'jdnwviuwh@gmail.com', N'male', N'9548649444', N'adhar card')
SET IDENTITY_INSERT [dbo].[CustomerMaster] OFF
